# Generated by Django 3.1.4 on 2021-01-30 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Person Name')),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=100, unique=True, verbose_name='Mobile No')),
                ('Gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('others', 'OTHERS')], max_length=50)),
                ('confirmation', models.BooleanField(verbose_name='I agree term & condition')),
                ('published_date', models.DateField()),
            ],
        ),
    ]
