# Generated by Django 3.1.4 on 2021-01-30 05:51

import campaign.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='email',
            field=models.EmailField(max_length=100, validators=[campaign.validators.gmail_validator]),
        ),
    ]
